### PR TITLE
WIP: Try adding social metadata

### PR DESCRIPTION
**Pull request by Chomtana**
Not sure if it working or not

### CODE REVIEW

**Comment by Chomtana** [comment]
It not working :(

**Comment by georgically** [comment]
> It not working :(

I think you will only know if the PR is merged?

**Comment by bluenex** [comment]
Looking at [the debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-21--lucid-hoover-526812.netlify.com%2F), it is working now.

image

However, what we need to fix is the image itself. Our current image has no background color, and it renders as white in the og-image. Another thing is the resolution. According to the [official guide](https://developers.facebook.com/docs/sharing/webmasters/images/), the image size for sharing should be 1200 x 630 or at least 600 x 315. I will try fixing this.

**Comment by bluenex** [comment]
image

Facebook is now working.

**Pull request merged**
